### ISSUE TITLE
Use compile-time solutions where possible

### ISSUE THREAD

**Issue by SuperV1234** [miguelmartin75/anax#20]
Ideas [taken from my WIP component-based entity system](https://github.com/SuperV1234/SSVBloodshed/tree/master/include/SSVBloodshed/CESystem).

Currently, in **anax**'s systems, processing requires getting the components from the entity. 

```cpp
// pseudocode
void process(Entity& e)
{
    auto& component1 = e.getComponent<T1>();
    auto& component2 = e.getComponent<T2>();
    // ...
    // But we already "know" where component1 and component2 are
}
```

This is unnecessary.

We can kill two birds with one stone if we use variadic templates to define system requirements instead of `ComponentFilter`.

```cpp
// MovementSystem acts on entities that have both CPosition
// and CVelocity but not CStatic
class MovementSystem : System<MovementSystem, 
    Requires<CPosition, CVelocity>, Excluding<CStatic>>
{
    // Do not store entities - store tuples of what is needed
    // std::vector<Entity*> entities;
    // Ideally this will be done internally in the System base class
    // Look at my WIP component system for an implementation
    using TupleType = std::tuple<Entity&, CPosition&, CVelocity&>;
    std::vector<TupleType> tuples;

    void process(TupleType& tuple)
    {
         auto& entity = std::get<0>;
         auto& cPosition = std::get<1>;
         auto& cVelocity = std::get<2>;
         // No need to query the entity for components -
         // we can get them more quickly from tuples
    }
};
```

**Comment by miguelmartin75** [comment]
I am now doing this in 2.0.0. However, I do not use tuples to store the components. I do wonder if it is faster (performance wise) for a tuple, but overall it is a good abstraction in general. Though, if I were to do this, I would probably turn remove the wrapper `Entity` over `Entity::Id` and just make `Entity` be `Entity::Id` instead.

You can essentially write the above example, like so:

```c++
struct MovementSystem : anax::System<anax::Requires<CPosition, CVelocity>, anax::Excludes<CStatic>>
{
    // access via getEntities()
};
```

**Comment by SuperV1234** [comment]
Great improvement over the previous syntax/semantics, in my opinion.

I've given a talk at CppCon 2015 last Monday regarding data-oriented component-based entity systems with C++14 *([you can find the code/slides here](https://github.com/SuperV1234/cppcon2015), and a recording of the talk will be updated roughly one month away from now)*, and I use compile-time solutions there to automatically generate data-structures and bitsets to do entity-matching.

Hope you can find something interesting in the code/slides.
