### ISSUE TITLE
ANAX_VIRTUAL_DTORS_IN_COMPONENT causes mysterious behavior

### ISSUE THREAD

**Issue by phaikawl** [miguelmartin75/anax#62]
I've been scratching my head with a very mysterious issue regarding `ANAX_VIRTUAL_DTORS_IN_COMPONENT`'s use in anax's `Component` class.

I have `ANAX_VIRTUAL_DTORS_IN_COMPONENT` set as *defined* in the cmake-generated `anax/Config.hpp`. So in anax's compilation units, `ANAX_VIRTUAL_DTORS_IN_COMPONENT` is **defined**, and anax's `Component` struct has its destructor declared as `virtual`.

In my code I have a component struct called `CameraComponent` in `CameraComponent.h`. The issue arises if I don't `#include` `anax/Config.hpp` in my `CameraComponent.h`, so `ANAX_VIRTUAL_DTORS_IN_COMPONENT` would be **undefined** in my code's compilation unit, and anax's `Component` struct would have its destructor NOT `virtual``.

That inconsistency regarding the `virtual`-ness of anax's `Component` definition would make my `CameraComponent` become a crazy struct with its fields completely messed up when passed as a parameter into a method of some other class (for example when I access `camera.m_lookat.x` in that method it would return `camera.fov`, completely nonsense).

It costed me a whole afternoon to figure that out. I believe `anax/Config.hpp` should be included somewhere along with `anax/Component.h` to avoid this happening again for other people.

I'm still not sure what is the exact reason behind that small inconsistency causing such weird behavior. Could someone tell me the reason? I thought gcc had a bug a something, but I changed the compiler to clang and it's still the same.

**Comment by miguelmartin75** [comment]
>It costed me a whole afternoon to figure that out. I believe anax/Config.hpp should be included somewhere along with anax/Component.h to avoid this happening again for other people.

Yeah, you are correct. Nice catch. Sorry about the time waste.

>That inconsistency regarding the virtual-ness of anax's Component definition would make my CameraComponent become a crazy struct with its fields completely messed up when passed as a parameter into a method of some other class (for example when I access camera.m_lookat.x in that method it would return camera.fov, completely nonsense).

That's weird, never run into that sort of bug regarding virtual destructors. I suppose it makes some-what sense. My only guess of why this occurs, is because it offsets your fields due to the object not containing a v-table (?). Odd that it even compiles, tbh.

Oh well, thanks for the bug report.
