### ISSUE TITLE
Problem Building for iOS (armv7, arm64, Xcode 7)

### ISSUE THREAD

**Issue by mrPurr** [miguelmartin75/anax#64]
I am trying to build the library for my iOS project which will only run on 64bit devices (A7 chip or higher).
Using the default cmake build script the library is build for the architectures i386 and x86_64.
Using Xcode 7 I get the errors:

> Undefined symbols for architecture x86\_64

> building for iOS simulator, but linking in object file built for OSX, for architecture x86\_64

I found this blog post on the issue: https://karp.id.au/post/xcode_7_linker_rules/

## Solution for the Simulator

The solution is to edit CMakeLists.txt like this:
add: `SET(IOS_VERSION_MIN_FLAG "-miphoneos-version-min=7.0")`

change: `#Make sure we're compiling with C++11
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${IOS_VERSION_MIN_FLAG} -std=c++11")`

Now `otool -lv libanax_s.a | grep LC_VERSION` prints: `cmd LC_VERSION_MIN_IPHONEOS`

This works fine on the simulator but not on an actual device. How do I build this for **armv7** and **arm64** architecture? 
This does not work: `set_target_properties(${ANAX_LIBRARY_NAME} PROPERTIES OSX_ARCHITECTURES "armv7;arm64;")`

**Comment by miguelmartin75** [comment]
To be quite honest, I'm not sure how to compile it for *both* armv7 and arm64 into one binary. However, what you could possibly do is use the lipo tool to combine the binaries for the simulator and the device separately. 

i.e. 

1. Compile the library separately: one for the simulator and one for the physical device.
2. Use the lipo tool to combine them, e.g.:
     ```
     lipo -create -output libanax_universal.a libanax_arm64.a libanax_arm7.a
     ```

I'm not quite sure that this will work, but I think it should. But again, I'm not sure how to do this directly in CMake.

**Comment by mrPurr** [comment]
Thanks, I got it to work following the instructions described here:
https://github.com/libical/libical/wiki/For-the-Users:-Build-for-Different-Platforms
