### ISSUE TITLE
Ability to add components in runtime

### ISSUE THREAD

**Issue by binaryzebra** [miguelmartin75/anax#67]
Am I understand correctly that I can't add components with dynamic typing?
If not you lose most of the benefits of the Entity Component Systems approach.

**Comment by miguelmartin75** [comment]
Of course you can? e.g. if you're referring to adding components via a scripting language like so:

```
e.setPosition({1, 2, 3});
```

Then `setPosition` would simply map to `addComponent<PositionComponent>`.

**Comment by binaryzebra** [comment]
Agreed. After detail look I understand how everything works.
