### ISSUE TITLE
[Question] Is "onEntityRemoved" called when doing Entity::deactivate ?

### ISSUE THREAD

**Issue by S6066** [miguelmartin75/anax#71]
Hello,
Everything is in the title, is the onEntityRemoved function (in a system) is called when deactivating an entity or is it only when killing it ?
Thanks.

**Comment by Shokwav** [comment]
In World::refresh:

`        // Go thru all the deactivated Entities from last call to refresh
        for(auto& entity: m_entityCache.deactivated){
            auto& attribute = m_entityAttributes.attributes[entity.getId().index]; 
            attribute.activated = false;

            // Loop through all the Systems within the World
            for(auto& i: m_systems){
                auto systemIndex = i.first;
                if((attribute.systems.size() > systemIndex) and attribute.systems[systemIndex]){
                    **i.second -> remove(entity);**
                    attribute.systems[systemIndex] = false;
                }
            }
        }`

You can see by the bolded line that onEntityRemoved is indeed called for deactivated entities.
