### ISSUE TITLE
Is this resource being developed?

### ISSUE THREAD

**Issue by Sithdown** [miguelmartin75/anax#79]
I'm deciding which entity system to use on an upcoming project, and anax looks like a good choice based on my needs, provided updates keep being pushed to it. I'm unsure about its development status, though.

Is this project active or should I continue my search? Thanks.

**Comment by miguelmartin75** [comment]
I would not say I am actively developing anax. If there is any major bugs that arise I am more than happy to fix them. Unfortunately the reason for such is simply because I just don't have the time. Feel free to use it or don't.

**Comment by Sithdown** [comment]
I was thinking in the lines of bugfixing, so that seems fine. I suppose I could do some PRs if needed once I come to know the library better. Thank you for your efforts!
