### ISSUE TITLE
Entity Templates

### ISSUE THREAD

**Issue by jupart** [miguelmartin75/anax#85]
Hello! I've been making use of your anax library in a side scrolling game I'm developing. I've come across a need to create similar entities sharing the same components (a bunch of one type of entity in other words), so I'd like to make use of your World::createEntity(EntityTemplateFn fn, Args&&... args) function, but I'm not quite sure of it's intended use. Would you mind explaining how you expect users to use it? Thanks!

**Comment by miguelmartin75** [comment]
If you view the [source](https://github.com/miguelmartin75/anax/blob/master/include/anax/World.hpp#L115), all it boils down to is: (1) create a new entity and (2) call the functor you provide it with.

So basically to make a "template" in this context you make a function that adds components to the entity. Then you pass the function to `createEntity` along with any parameters you want to pass to the function that creates the entity.
