### ISSUE TITLE
anax::World world; fails

### ISSUE THREAD

**Issue by kishkumen123** [miguelmartin75/anax#86]
Sorry if this is unconventional but your email domain and website don't work in order for me to contact you. I'm trying to use your library, I installed it as directed, I installed boost. I #include <anax/anax.hpp>.

I'm using sfml. When I compile with out calling world it compiles fine, but when I do anax::World world; as directed in your tutorial, when I compile I get this error message:
*****************************
rm -f ./bin/pacman
g++ -std=c++0x -Wall main.cpp windowmanager.cpp -o ./bin/pacman  -lsfml-graphics -lsfml-window -lsfml-system 
/tmp/cc8rkjqw.o: In function `main':
main.cpp:(.text+0xef): undefined reference to `anax::World::World()'
/tmp/cc8rkjqw.o: In function `std::unique_ptr<anax::detail::BaseSystem, anax::World::SystemDeleter>::~unique_ptr()':
main.cpp:(.text._ZNSt10unique_ptrIN4anax6detail10BaseSystemENS0_5World13SystemDeleterEED2Ev[_ZNSt10unique_ptrIN4anax6detail10BaseSystemENS0_5World13SystemDeleterEED5Ev]+0x43): undefined reference to `anax::World::SystemDeleter::operator()(anax::detail::BaseSystem*) const'
collect2: error: ld returned 1 exit status
Makefile:19: recipe for target 'bin/pacman' failed
make: *** [bin/pacman] Error 1
*****************************
ERROR:
![image](https://cloud.githubusercontent.com/assets/3270002/24834992/5d19ad6c-1cba-11e7-9035-70e36b69a8c6.png)

CODE:
![image](https://cloud.githubusercontent.com/assets/3270002/24834997/775ff032-1cba-11e7-90b5-48eaa84aa9ca.png)

**Comment by miguelmartin75** [comment]
Thanks for highlighting the issue about my website. 

Your compiler error highlights the issue:

```
/tmp/cc8rkjqw.o: In function main': main.cpp:(.text+0xef): undefined reference to anax::World::World()'
```

To highlight the error further it mentions ` undefined reference to anax::World::World()'`. Now an undefined reference simply means that there is no definition. In this case it's the World class's constructor. The reason that this is the case is that you are not linking to anax.

To resolve this issue simply pass `-lanax` to your compiler.
