### ISSUE TITLE
Can you save some markup? Anax seems very verbose

### ISSUE THREAD

**Issue by kim366** [miguelmartin75/anax#92]
Sorry for writing it here, I think I am abusing the functionality of GitHub's issues again, but there is no forum or chat.

In [this example](https://github.com/miguelmartin75/anax/tree/master/examples/4%20Collision) the systesm are first declared

```
SpriteRenderingSystem m_spriteRenderingSystem;
AnimationSystem m_animationSystem;
MovementSystem m_movementSystem;
PlayerInputSystem m_playerInputSystem;
CollisionSystem m_collisionSystem;
```

then added to the world

```
m_world.addSystem(m_spriteRenderingSystem);
m_world.addSystem(m_animationSystem);
m_world.addSystem(m_playerInputSystem);
m_world.addSystem(m_movementSystem);	
m_world.addSystem(m_collisionSystem);
```

and then their `update` method is called every frame

```
m_collisionSystem.update(deltaTime);	
m_animationSystem.update(deltaTime);
m_playerInputSystem.update(deltaTime);
m_movementSystem.update(deltaTime);
```

And this is just from a simple example.

I thought about having a container (like `std::vector`), which would cut down on the latter two snippets, which could be replaced with a for-loop, but the data types are different for all of them. I haven't worked with this yet, but maybe `std::any` or having them be pointers of a base type that all systems inherit from?

What's your input?

**Comment by miguelmartin75** [comment]
Probably could with a std::tuple and polymorphic lambdas with the way it currently is. Can't with a vector as update is not virtual.

**Comment by kim366** [comment]
The update could be made virtual, though, couldn't it? And then with a vector of pointers to children of an abstract class, the method could be called in a loop.

**Comment by miguelmartin75** [comment]
Well of course, but I think my reasoning back then was because you incur the cost of the virtual table lookup. Which looking at it now, is negligible, but back then I was adamant in minimizing the use of virtual functions.
