### ISSUE TITLE
Linker Errors VS2017. Not sure what's wrong?

### ISSUE THREAD

**Issue by Jasonfran** [miguelmartin75/anax#93]
`LNK2019	unresolved external symbol "public: void __thiscall anax::World::SystemDeleter::operator()(class anax::detail::BaseSystem *)const " (??RSystemDeleter@World@anax@@QBEXPAVBaseSystem@detail@2@@Z) referenced in function "public: __thiscall std::unique_ptr<class anax::detail::BaseSystem,struct anax::World::SystemDeleter>::~unique_ptr<class anax::detail::BaseSystem,struct anax::World::SystemDeleter>(void)" (??1?$unique_ptr@VBaseSystem@detail@anax@@USystemDeleter@World@3@@std@@QAE@XZ)`

Getting this whenever using `anax::World`. I've used both Visual Studio and mingw32-make and get the same results. I get the DLL and put it in the .exe directory. I feel like there should be a .lib file but I don't get any?

**Comment by miguelmartin75** [comment]
Within your Visual Studio project you have to change your linker settings to link to the DLL you compiled, otherwise you will get linker errors complaining that it can't find the implementation.

**Comment by Jasonfran** [comment]
Everything I've found suggests there needs to be a .lib file for Visual Studio to import the library. That's how every other library I've used works. I'm not sure what to do here. Looks like someone else had the same problem #78
