### ISSUE TITLE
Get entity by ID

### ISSUE THREAD

**Issue by fnc12** [miguelmartin75/anax#99]
The only thing I found is getting entity by index, but I have ID. How?

**Comment by miguelmartin75** [comment]
You can get the index from the ID via `id.index`.

https://github.com/miguelmartin75/anax/blob/11d310cdcae8a343171dd9b03b573781893d27f1/tests/Test_Entities.cpp#L387-L388

**Comment by fnc12** [comment]
The question is "how to get entity by Id::value". I have `uint64_t` value 65345. How to get entity by this int value?

**Comment by miguelmartin75** [comment]
My previous comment has usage of what you're asking to do:

```
auto e2 = world.getEntity(e1.getId().index); 
```
